# Build stage
FROM gradle:8-jdk21-alpine AS builder

# Set the working directory
WORKDIR /app


RUN ls 
# Copy Gradle wrapper and build files
COPY gradlew build.gradle.kts settings.gradle.kts  ./
COPY gradle ./gradle/
RUN ls 

RUN chmod -R 755 gradlew ./gradle

RUN ls -R ./gradle


# Copy the source code
COPY src/ ./src/

# Build the application
RUN ./gradlew build --no-daemon

#RUN ./gradlew bootJar --no-daemon
RUN ls -R 
RUN ls -R /app/build/libs
RUN ls -R /app/
# Runtime stage
FROM openjdk:21-slim

# Set the working directory
WORKDIR /app
RUN ls -R /app

# Copy the built JAR from the builder stage
COPY --from=builder /app/build/libs/cloudruntekton-0.0.1-SNAPSHOT.jar app.jar

# Expose the application port
EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
	