# Build stage
FROM gradle:8-jdk21-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy Gradle wrapper and build files
COPY gradlew build.gradle2.kts settings.gradle.kts gradle/ ./

RUN chmod -R +x gradlew gradle

RUN ls -R gradle/wrapper


# Copy the source code
COPY src/ ./src/

# Build the application
RUN ./gradlew build --no-daemon

# Runtime stage
FROM openjdk:21-slim

# Set the working directory
WORKDIR /app

# Copy the built JAR from the builder stage
COPY --from=builder /app/build/libs/*.jar app.jar

# Expose the application port
EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
